name: dscript

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.10
  - pip
  - pytorch>=1.13
  - biotite==1.4.0
  - h5py
  - huggingface_hub
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - tqdm
  - loguru
  - pip:
    - -e .
