name: Documentation Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs-build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"
        
    - name: Build documentation
      working-directory: docs
      run: |
        # Build HTML documentation with warnings treated as errors
        sphinx-build -W -b html source build/html
        
    - name: Check for build artifacts
      run: |
        # Verify that the documentation was built successfully
        if [ ! -f "docs/build/html/index.html" ]; then
          echo "Error: Documentation build failed - index.html not found"
          exit 1
        fi
        echo "Documentation build completed successfully"
        
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: documentation-html
        path: docs/build/html/
        retention-days: 30
